export const NEW_CAROUSEL_REQUEST = "NEW_CAROUSEL_REQUEST"
export const NEW_CAROUSEL_SUCCESS = "NEW_CAROUSEL_SUCCESS"
export const NEW_CAROUSEL_FAIL = "NEW_CAROUSEL_FAIL"
export const NEW_CAROUSEL_RESET = "NEW_CAROUSEL_RESET"

export const UPDATE_CAROUSEL_REQUEST = "UPDATE_CAROUSEL_REQUEST"
export const UPDATE_CAROUSEL_SUCCESS = "UPDATE_CAROUSEL_SUCCESS"
export const UPDATE_CAROUSEL_FAIL = "UPDATE_CAROUSEL_FAIL"
export const UPDATE_CAROUSEL_RESET = "UPDATE_CAROUSEL_RESET"

export const DELETE_CAROUSEL_REQUEST = "DELETE_CAROUSEL_REQUEST"
export const DELETE_CAROUSEL_SUCCESS = "DELETE_CAROUSEL_SUCCESS"
export const DELETE_CAROUSEL_FAIL = "DELETE_CAROUSEL_FAIL"
export const DELETE_CAROUSEL_RESET = "DELETE_CAROUSEL_RESET"

export const CATEGORY_CAROUSEL_REQUEST = "CATEGORY_CAROUSEL_REQUEST"
export const CATEGORY_CAROUSEL_SUCCESS = "CATEGORY_CAROUSEL_SUCCESS"
export const CATEGORY_CAROUSEL_FAIL = "CATEGORY_CAROUSEL_FAIL"