export const NEW_DEAL_REQUEST = "NEW_DEAL_REQUEST"
export const NEW_DEAL_SUCCESS = "NEW_DEAL_SUCCESS"
export const NEW_DEAL_FAIL = "NEW_DEAL_FAIL"
export const NEW_DEAL_RESET = "NEW_DEAL_RESET"

export const UPDATE_DEAL_REQUEST = "UPDATE_DEAL_REQUEST"
export const UPDATE_DEAL_SUCCESS = "UPDATE_DEAL_SUCCESS"
export const UPDATE_DEAL_FAIL = "UPDATE_DEAL_FAIL"
export const UPDATE_DEAL_RESET = "UPDATE_DEAL_RESET"

export const DELETE_DEAL_REQUEST = "DELETE_DEAL_REQUEST"
export const DELETE_DEAL_SUCCESS = "DELETE_DEAL_SUCCESS"
export const DELETE_DEAL_FAIL = "DELETE_DEAL_FAIL"
export const DELETE_DEAL_RESET = "DELETE_DEAL_RESET"

export const CATEGORY_DEAL_REQUEST = "CATEGORY_DEAL_REQUEST"
export const CATEGORY_DEAL_SUCCESS = "CATEGORY_DEAL_SUCCESS"
export const CATEGORY_DEAL_FAIL = "CATEGORY_DEAL_FAIL"