export const NEW_TRENDING_REQUEST = "NEW_TRENDING_REQUEST"
export const NEW_TRENDING_SUCCESS = "NEW_TRENDING_SUCCESS"
export const NEW_TRENDING_FAIL = "NEW_TRENDING_FAIL"
export const NEW_TRENDING_RESET = "NEW_TRENDING_RESET"

export const UPDATE_TRENDING_REQUEST = "UPDATE_TRENDING_REQUEST"
export const UPDATE_TRENDING_SUCCESS = "UPDATE_TRENDING_SUCCESS"
export const UPDATE_TRENDING_FAIL = "UPDATE_TRENDING_FAIL"
export const UPDATE_TRENDING_RESET = "UPDATE_TRENDING_RESET"

export const DELETE_TRENDING_REQUEST = "DELETE_TRENDING_REQUEST"
export const DELETE_TRENDING_SUCCESS = "DELETE_TRENDING_SUCCESS"
export const DELETE_TRENDING_FAIL = "DELETE_TRENDING_FAIL"
export const DELETE_TRENDING_RESET = "DELETE_TRENDING_RESET"

export const CATEGORY_TRENDING_REQUEST = "CATEGORY_TRENDING_REQUEST"
export const CATEGORY_TRENDING_SUCCESS = "CATEGORY_TRENDING_SUCCESS"
export const CATEGORY_TRENDING_FAIL = "CATEGORY_TRENDING_FAIL"