export const NEW_ADDRESS_REQUEST = "NEW_ADDRESS_REQUEST"
export const NEW_ADDRESS_SUCCESS = "NEW_ADDRESS_SUCCESS"
export const NEW_ADDRESS_FAIL = "NEW_ADDRESS_FAIL"
export const NEW_ADDRESS_RESET = "NEW_ADDRESS_RESET"

export const USER_ADDRESSES_REQUEST = "USER_ADDRESSES_REQUEST"
export const USER_ADDRESSES_SUCCESS = "USER_ADDRESSES_SUCCESS"
export const USER_ADDRESSES_FAIL = "USER_ADDRESSES_FAIL"

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST"
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS"
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL"
export const DELETE_ADDRESS_RESET = "DELETE_ADDRESS_RESET"

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST"
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS"
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL"
export const UPDATE_ADDRESS_RESET = "UPDATE_ADDRESS_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"