export const NEW_CAROUSEL_REQUEST = "NEW_CAROUSEL_REQUEST"
export const NEW_CAROUSEL_SUCCESS = "NEW_CAROUSEL_SUCCESS"
export const NEW_CAROUSEL_FAIL = "NEW_CAROUSEL_FAIL"
export const NEW_CAROUSEL_RESET = "NEW_CAROUSEL_RESET"

export const ALL_CAROUSEL_REQUEST = "ALL_CAROUSEL_REQUEST"
export const ALL_CAROUSEL_SUCCESS = "ALL_CAROUSEL_SUCCESS"
export const ALL_CAROUSEL_FAIL = "ALL_CAROUSEL_FAIL"