export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"

export const USER_CARTS_REQUEST = 'USER_CARTS_REQUEST'
export const USER_CARTS_SUCCESS = "USER_CARTS_SUCCESS"
export const USER_CARTS_FAIL = "USER_CARTS_FAIL"

export const REMOVE_CART_REQUEST = "REMOVE_CART_REQUEST"
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS"
export const REMOVE_CART_RESET = "REMOVE_CART_RESET"
export const REMOVE_CART_FAIL = "REMOVE_CART_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"