export const NEW_CUSTOM_PRODUCT_REQUEST = "NEW_CUSTOM_PRODUCT_REQUEST"
export const NEW_CUSTOM_PRODUCT_SUCCESS = "NEW_CUSTOM_PRODUCT_SUCCESS"
export const NEW_CUSTOM_PRODUCT_FAIL = "NEW_CUSTOM_PRODUCT_FAIL"
export const NEW_CUSTOM_PRODUCT_RESET = "NEW_CUSTOM_PRODUCT_RESET"

export const USER_CUSTOM_PRODUCTS_REQUEST = "USER_CUSTOM_PRODUCTS_REQUEST"
export const USER_CUSTOM_PRODUCTS_SUCCESS = "USER_CUSTOM_PRODUCTS_SUCCESS"
export const USER_CUSTOM_PRODUCTS_FAIL = "USER_CUSTOM_PRODUCTS_FAIL"

export const UPDATE_CUSTOM_PRODUCT_REQUEST = "UPDATE_CUSTOM_PRODUCT_REQUESTv"
export const UPDATE_CUSTOM_PRODUCT_SUCCESS = "UPDATE_CUSTOM_PRODUCT_SUCCESS"
export const UPDATE_CUSTOM_PRODUCT_FAIL = "UPDATE_CUSTOM_PRODUCT_FAIL"
export const UPDATE_CUSTOM_PRODUCT_RESET = "UPDATE_CUSTOM_PRODUCT_RESET"

export const DELETE_CUSTOM_PRODUCT_REQUEST = "DELETE_CUSTOM_PRODUCT_REQUEST"
export const DELETE_CUSTOM_PRODUCT_SUCCESS = "DELETE_CUSTOM_PRODUCT_SUCCESS"
export const DELETE_CUSTOM_PRODUCT_FAIL = "DELETE_CUSTOM_PRODUCT_FAIL"
export const DELETE_CUSTOM_PRODUCT_RESET = "DELETE_CUSTOM_PRODUCT_RESET"

export const COLLECT_CUSTOM_PRODUCT_DATA = "COLLECT_CUSTOM_PRODUCT_DATA"