export const NEW_ORDER_REQUEST = "NEW_ORDER_REQUEST"
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS"
export const NEW_ORDER_FAIL = "NEW_ORDER_FAIL"
export const NEW_ORDER_RESET = "NEW_ORDER_RESET"

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST"
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS"
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"