export const NEW_ORDER_REQUEST = "NEW_ORDER_REQUEST"
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS"
export const NEW_ORDER_FAIL = "NEW_ORDER_FAIL"
export const NEW_ORDER_RESET = "NEW_ORDER_RESET"

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET"

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST"
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS"
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL"

export const COLLECT_OREDER_DATA = "COLLECT_OREDER_DATA"

export const CLEAR_ERRORS = "CLEAR_ERRORS"