const NEW_PAGE_REQUEST = "NEW_PAGE_REQUEST"
const NEW_PAGE_SUCCESS = "NEW_PAGE_REQUEST"
const NEW_PAGE_FAIL = "NEW_PAGE_FAIL"
const NEW_PAGE_RESET = "NEW_PAGE_FAIL"

const PAGE_DETAILS_REQUEST = "PAGE_DETAILS_REQUEST"
const PAGE_DETAILS_SUCCESS = "PAGE_DETAILS_SUCCESS"
const PAGE_DETAILS_FAIL = "PAGE_DETAILS_FAIL"
