export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CERATE_PRODUCT_SUCCESS = "CERATE_PRODUCT_SUCCESS"
export const CERATE_PRODUCT_FAIL = "CERATE_PRODUCT_FAIL"
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET"

export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"