export const NEW_SIZE_REQUEST = "NEW_SIZE_REQUEST"
export const NEW_SIZE_SUCCESS = "NEW_SIZE_SUCCESS"
export const NEW_SIZE_FAIL = "NEW_SIZE_FAIL"
export const NEW_SIZE_RESET = "NEW_SIZE_RESET"

export const USER_SIZES_REQUEST = "USER_SIZES_REQUEST"
export const USER_SIZES_SUCCESS = "USER_SIZES_SUCCESS"
export const USER_SIZES_FAIL = "USER_SIZES_FAIL"

export const DELETE_SIZE_REQUEST = "DELETE_SIZE_REQUEST"
export const DELETE_SIZE_SUCCESS = "DELETE_SIZE_SUCCESS"
export const DELETE_SIZE_FAIL = "DELETE_SIZE_FAIL"
export const DELETE_SIZE_RESET = "DELETE_SIZE_RESET"

export const UPDATE_SIZE_REQUEST = "UPDATE_SIZE_REQUEST"
export const UPDATE_SIZE_SUCCESS = "UPDATE_SIZE_SUCCESS"
export const UPDATE_SIZE_FAIL = "UPDATE_SIZE_FAIL"
export const UPDATE_SIZE_RESET = "UPDATE_SIZE_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"